In [2]:
import numpy as np

In [3]:
# Creating Array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
# Multidimentional array
b = np.array([[10, 20, 30], [11, 22, 33]])
print(b)

[[10 20 30]
 [11 22 33]]


In [6]:
b[1, 2]

33

In [13]:
# Array of Zeros and Ones
i = np.zeros((2,3))
j = np.ones((3,3))
i, j

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [8]:
np.full((2,2), 11)

array([[11, 11],
       [11, 11]])

In [14]:
i = np.random.rand(3,2) # Array with random values
j = np.identity(3) # Identity Matrix

i, j

(array([[0.84777516, 0.24501478],
        [0.623791  , 0.80823386],
        [0.41764945, 0.68250685]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [20]:
#Inspecting Array

print(a.itemsize)
print(a.shape) # Dimention
print(a.ndim)  # Number of array Dimentions
print(a.dtype) # Data type of array elements

4
(3,)
1
int32


### Array Mathematics

In [29]:
x = np.array([1,2,3])
y = np.array([5,6,7])

print(x - y)     # Subtraction
np.subtract(a,b) # another method

print(x + y) # Addition
np.add(x, y)

print(x/y)   # Division
np.divide(x,y)

print(x * y) # Multiplicaiton
np.multiply(x,y)

np.exp(x)    # Exponential
np.sqrt(y)   # Square root
np.sin(x)    # Prints sines of an array
np.cos(y)    # Prints cosine of an array

np.log(x)    # Elementwise natural logarithm


[-4 -4 -4]
[ 6  8 10]
[0.2        0.33333333 0.42857143]
[ 5 12 21]


array([0.        , 0.69314718, 1.09861229])

### Comparison

In [32]:
print(a == b)
print(a < 2)

[[False False False]
 [False False False]]
[ True False False]


In [34]:
a = np.array([4,1,9,5])
a.sort()
print(a)

[1 4 5 9]


### Subsetting, Slicing, Indexing

In [60]:
# Subsetting
a = np.array([(1,2,3,4), (5,6,7,8)])
a[1]    # Selects element at 1st index 
a[1,2]  # 7

# Slicing
a[0:2]    # Select items at index 0 & 1
a[0:2, 1] # Select items at rows 0 & 1 in column 1

a[a<3]    # Select elements from a less than 2

array([1, 2])

### Array Manipulation

In [63]:
i = np.transpose(a)
i.T # Permutate array dimentions

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])